### ISSUE TITLE
[Neo/Forge 1.20.1 MV: 1.2.0] Trading with Piglin Travelers can cause an infinity freeze with nothing in the logs...

### ISSUE THREAD

**Issue by Jusey1** [seymourimadeit/Piglin-Proliferation#17]
Video:
https://github.com/seymourimadeit/Piglin-Proliferation/assets/61861078/aa16ecde-763f-41a2-b053-e4baab4da6b0

As shown in video, the game will do a complete lag-freeze where the client is confused but once the next trade is initiated, it completely bogs down into a complete frozen state with the game not responding anymore, have to use the Task Manager to close down Minecraft. However, no crash log is made and both the normal log and debug log shows nothing. I took a bit to post this bug report because I wanted to do intensive testing to see if I can get this issue to log literally anything but nothing is logged, it just completely breaks down and dies. I have literally nothing to show on how to figure out what is going on other than information about my modlist and what not which will be below...

Minecraft: 1.20.1
Neoforge: 47.1.104
Modlist: [Modlist.txt](https://github.com/seymourimadeit/Piglin-Proliferation/files/15211074/Modlist.txt)

I'm gonna keep trying to test things out and see if I can get a log created to help gather information.

**Comment by seymourimadeit** [comment]
Trying to debug this myself right now and no results so far so I will have to ask a few questions:
1. Does this just happen when trading with the traveler regularly?
2. Does this still happen when the mod is alone?
3. If not, what specific mods in your modlist are causing it?

I suggest you also try to do a thread dump while this bug is happening and send the .pid file generated as that can help us tremendously  (or send your mods.zip file if you can't figure that out)

**Comment by Jusey1** [comment]
Working on it right now, sorry. Was doing DnD for a while. Currently gonna do a test run with the mod by itself and gonna see if it happens due to a specific issue with another mod and go from there. Will update once I do heavy testings.

Will confirm, trading directly or dropping gold ingots causes the same issue no matter.

**Comment by seymourimadeit** [comment]
👍 

Yeah I was able to get a thread dump from a personal modpack I was playing and stuff is fucky wucky to say the least. What makes it even more so is the fact when I test it out in a dev environment it just works somehow. 

I'm trying to investigate more right now but real life is pooping on me hard so I don't know how soon the fix will be out, sorry for the convenience. 

My hunch is that somehow Yung's Fortress' is causing it, but that's just a tinfoil hat thing since we both have it in our modpacks (i also need to add it to the default config lmoa)

**Comment by Jusey1** [comment]
Yung's Better Fortress is not causing it. I currently have Yung's set of mods back into my pack and still no issues at all. Will continue testing. I am happy that none of my own mods are causing issues.

**Comment by Jusey1** [comment]
Okay, I deleted my last comment because yeah, it's an issue with Yung's Better Fortresses. I assume this is because the original Fortress is disabled while Yung's mod is installed, so that's probably what is causing the issue. Might need to add a different kind of check using a tag perhaps which has both the vanilla and Yung's Better Fortress within it? That's my guess.

**Comment by seymourimadeit** [comment]
[zipfilesogithubdoesntcomplain.zip](https://github.com/seymourimadeit/Piglin-Proliferation/files/15211772/zipfilesogithubdoesntcomplain.zip)

Thanks for the help so far, could you try this .jar file out? I just added the Yung's Better Fortress id into one of the tags. (its in a .zip file so you'll have to extract it and put it in manually)

**Comment by seymourimadeit** [comment]
Actually if that doesn't work I will probably have to manually make a separate data pack for this mod and place it front in center in the curseforge page (unless we think of a better solution) considering this seems like a whole issue with that mod.

https://github.com/YUNG-GANG/YUNGs-Better-Fortresses/issues/14

**Comment by Jusey1** [comment]
I thinking you could do an "is mod loaded" check and then either just use a different rag if Yung's Better Fortresses is loaded or modify the tag in java by removing "minecraft:fortress" and adding "betterfortress:fortress" automatically. The second idea would require an additional check to see if "minecraft:fortress" is currently tagged before removing and adding just in case if someone made a datapack to remove it themselves, then you wouldn't want the mod to automatically add the other tag.

But yeah, having "minecraft:fortress" tagged, no matter what, causes the crash unless it is currently generating in the game's world.

**Comment by flowerfugue** [comment]
Specifically completed in f6cb86b :)
