### ISSUE TITLE
buckler not working in latest 1.20.1

### ISSUE THREAD

**Issue by NotTohm** [seymourimadeit/Piglin-Proliferation#20]
i can charge it but it doesnt ever go and no i'm not in rainy weather or anything

**Comment by seymourimadeit** [comment]
Is this on an instance with just piglin proliferation or with more mods

**Comment by NotTohm** [comment]
its with other mods

**Comment by seymourimadeit** [comment]
You're gonna have to remove each mod one by mod until the culprit is found due to the nature of this bug not appearing with only this mod installed, then you'll have to report it to the other mod's github and list it here.

I'll try my best to fix the mod incompatibility issue once its found if it is fixable on this mod's side, if not it'll have to be fixed on the other mod's side.

**Comment by seymourimadeit** [comment]
I'm going to have to close this issue due to inactivity until further notice.

**Comment by NotTohm** [comment]
oh mb i forgot about this, ill see if i can figure it out rq
