### ISSUE TITLE
[1.21-Neo] Server crash when Piglins(Brute?) using the Buckler Item.

### ISSUE THREAD

**Issue by Gbergz** [seymourimadeit/Piglin-Proliferation#25]
### Versions
NeoForge: 21.0.30
Piglin Proliferation: 2.0.1 
(can't update to latest NeoForge right now due to breaking changes in forge and need to wait till other mods updated, this is in a modpack.)

### Crash Report
https://gist.githubusercontent.com/Gbergz/ecb0043fb30467b694ff002235c41b16/raw/699f7008352a651a156266a37e0d5444767b97a1/gistfile1.txt

**Comment by seymourimadeit** [comment]
One thing to note is that this bug fix is going to have to be packaged with the updates to make it compatible with newer neoforge versions as much as I'd love to allow it to be backwards compatible. Sorry about that, but I hope you can understand since neoforge is making a lot of breaking changes during this stage of porting.

**Comment by Gbergz** [comment]
I completely understand, thanks!
